from setuptools import setup, find_packages

setup(
    name="ama-intent",
    version="2.0.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.24.0",
        "pandas>=2.0.0",
        "matplotlib>=3.7.0",
        "psutil>=5.9.0",
        "tabulate>=0.9.0",
        "Flask==3.0.0",
        "Flask-CORS==4.0.0",
        "SQLAlchemy==2.0.23",
        "alembic==1.13.0",
        "PyJWT==2.8.0",
        "bcrypt==4.1.1",
        "python-dotenv==1.0.0",
        "requests==2.31.0",
        "python-dateutil==2.8.2",
        "colorlog==6.8.0",
        "gunicorn==21.2.0",
        "uvicorn==0.24.0",
        "passlib==1.7.4",
    ],
    author="AMA-Intent Team",
    description="Sistema de Cerebro Artificial Biomimético",
    python_requires=">=3.9",
)
